### ISSUE TITLE
[Avian2d] Compilation issue with v0.6.0-rc.1

### ISSUE THREAD

**Issue by Galdormin** [Jondolf/avian#943]
Avian2d cannot compile in v0.6.0-rc.1. I suppose it is due to a conflict in the version of `glam`.

The example below can compile in v0.5.0 but not in v0.6.0-rc.1.

## How to reproduce

- `Cargo.toml`
```
[package]
name = "test_bevy_avian"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.6.0-rc.1"
bevy = "0.18.0"
```

- `main.rs`
```rust
use bevy::prelude::*;

use avian2d::prelude::*;

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, PhysicsPlugins::default()))
        .run();
}
```

- `cargor tree -d`:
```
glam v0.30.10
├── bevy_math v0.18.0 (*)
├── bevy_reflect v0.18.0 (*)
├── bevy_render v0.18.0 (*)
├── glam_matrix_extras v0.2.0 (*)
├── glamx v0.1.3
│   └── parry2d v0.26.0 (*)
├── hexasphere v16.0.0
│   └── bevy_mesh v0.18.0 (*)
└── obvhs v0.3.0
    └── avian2d v0.6.0-rc.1 (*)

glam v0.31.1
└── avian2d v0.6.0-rc.1 (*)
```

- Error:
  - `error[E0277]: cannot subtract/add/multiply 'glam::Vec3A' from 'bevy_math::Vec3A'`
  - `error[E0282]: type annotations needed`
